### ISSUE TITLE
Creating character

### ISSUE THREAD

**Issue by MarioCamMen** [Althea21/witcher_fg_ruleset#12]
Chose to create a Witcher PC
1. When selecting "Witcher"race, the profession should be set as Witcher as well
2. Social standing should be depending on the place the campaign is happening... shouldn't this be a "check box"controlled by the GM?
2.1. STA and HP are not calculated correctly (should check the formula)
3. Would it work that, after selecting class and race, all abilities "bonuses" are added automatically? (for example: the +1 to REF and DEX and the -4 to EMP for Witchers)
3.1. I cannot edit the SKILLS values. Maybe it will also help that class skills are automatically highlighted and "cross-skills" are selected manually
3.2. Can a "pool point" be added and substracted when editing the skills? (to avoid PCs to go over a limit at level 1)
4. Cannot add Witcher "magical class" in the "Spells"section. Shouldn't it be added automatically and just in the case of Mages/Clerics drag and drop the desired spells (drag and drop mage spells work as far as I checked but not signs even if mages can learn them)

Others:
1. Only dices used are d10 and d6... is there a way to remove the others to avoid PC using
2. Automated Backgound generator would be fun to add (PCs roll)
3. Skill tree for each Profession should be a different tab
4. Could not find items to add weapons and armors, so I guess that will come after :)

**Comment by Althea21** [comment]
Hello,  

First thank you for your feedback :) 
Here's some responses :

1. I didn't force this to let more freedom to players (I'm sure some will come with exotic profile, like say Karadine in the game, if the GM allow it, the ruleset shouldn't prevent it). Also a "custom class" will be added to allow homebrew classes (and new offical classes between releases, like the noble which you can add for the moment)

2. Why would you let only the GM control social standing ? It could be changed during the game if the party travel to other part of the world that should affect their social standing.
    2.1 will check this, thanks 

3. Class automations will be implemented in later versions. 
    3.1 problem of read only skills has been corrected (issue #9 )
    3.2 As there's no such thing as an explicit level it's complicated to force this. Let say a player reroll during a campaign and the GM let him create an experienced PC for him to not fall behind the rest of the party , this could be impossible if we cap the PC at the creation. 

4. Can you give me more information about this ? When you create a magical class and you click on the icon before the title, it should cycle between the different class (as in the 3.5/Pathfinder ruleset). Each class should only allow drop of according spells.

Others :

1. Will surely add an option for this later
2. Lifepath tab will be added, I'm not sure about the level of automation that will be implemented for now
3. The skills tab is currently under reconstruction, I will keep your idea in mind.
4. Yes a Gear module is planned later (it's a lot of content to add :) )

Thanks again for your feedback, 
Althea

**Comment by MarioCamMen** [comment]
Hi Althea,



Thanks for replying so fast!! I am really excited about this module you are
creating and want to provide as much help as I can. Sadly, I don't know a
penny about programming but I've been role-playing for a long time so I
hope my feedback as a player/GM can be useful :) I’m also a big Witcher
enthusiast (books, comics and all existing games) so double happy to help!!



As I was writing more comments/ideas I just realized about the huge work
that developing this involves, so I’d like to congratulate you (and your
team if any) for the effort you are putting into it!!



Btw, sorry if sometimes I write funny, English is not my mother tongue :P



Some new ideas/comments first:



1. The character "main" sheet seems a bit empty... would it help to make
the font a bit bigger and also add to the tab more graphs/images? For
example, make the PC portrait bigger, leave more space between the portrait
and the starting text, maybe add images for Gender and Profession to make
it more visual?



1.1. For Witcher profession... do you plan to add a "Witcher school" option
that gets visible after you selected Witcher as race/profession? This way
you could also automate the benefits based on school of choosing... and if
the "more visual" idea is appealing to you, maybe display the medallion
image accordingly ;)



2. Maybe the Skill tab can also display the BASE + MOD = TOTAL so the it is
easier to spot the allocated points (both at the character creation as well
as the game progresses). MOD value can be auto filled based on
Race/Profession (such as the +2 bonus in Archery for Elves or the Dwarves
+1 in Physique)… Probably add to the display a MISC box (BASE+MOD+MISC =
TOTAL) to the format? MISC could also include bonus due to Lifepath



3. Are you planning to add a place where PCs can add and visualize the
specific racial PERKS in the main tab or any other tab?



4. Shouldn’t VIGOR be displayed only at the SPELLS tab? Instead of both
MAIN and SPELLS?



5. Will you include an “information button” next to skills/perks and such
so that the player can click and read quickly to remember what things do?



6. Regarding combat. The D&D FG module has it easy, as the attack is
compared to a fixed AC value and, if greater, then is a hit and damaged can
be rolled and then subtracted from the total HPs of the target. Since The
Witcher has several attack options and roll-dependent defensive options…
are you planning to automate this by requesting the targeted character to
roll the desired defensive action after the attack value has been
calculated and after the roll then automatically calculate the outcome?

For example:

Step 1: Monster attacks PC, so GM clicks to roll monster attack… then value
is calculated and displayed (possibly)

Step 2: PC decides which defensive action to take and clicks BLOCK (for
example)… after clicking BLOCK the value is calculated and displayed

Step 3: Both values are compared (automatically) and outcome is resolved…

Step 4: Proceed to damage armor, weapon (in case of blocking) and possibly
HP



7. Will you add an “action” button for Actively Dodge or Aim actions, so
that benefits are calculated automatically… maybe as a 1 round condition
that could be set by the PC?



8. Will you add Brawling & Wrestling and Special attack buttons/options/?



9. Don’t want to start harassing you with Verbal combat, Wounds, Critical
fumbles, and other stuff yet ☹


Some comments on top of yours:

1.     I didn't force this to let more freedom to players (I'm sure some
will come with exotic profile, like say Karadine in the game, if the GM
allow it, the ruleset shouldn't prevent it). Also a "custom class" will be
added to allow homebrew classes (and new offical classes between releases,
like the noble which you can add for the moment) - *got it and love the
idea!*

2.     Why would you let only the GM control social standing ? It could be
changed during the game if the party travel to other part of the world that
should affect their social standing. - *I think you are right :)*
2.1 will check this, thanks - *Today I loaded my saved game and the values
were recalculated correctly... don't know what happened*

3.     Class automations will be implemented in later versions. - *Awesome *
3.1 problem of read only skills has been corrected (issue #9
<https://github.com/Althea21/witcher_fg_ruleset/issues/9> ) - *got it!*
3.2 As there's no such thing as an explicit level it's complicated to force
this. Let say a player reroll during a campaign and the GM let him create
an experienced PC for him to not fall behind the rest of the party , this
could be impossible if we cap the PC at the creation. - *Agree*

4.     Can you give me more information about this ? When you create a
magical class and you click on the icon before the title, it should cycle
between the different class (as in the 3.5/Pathfinder ruleset). Each class
should only allow drop of according spells. - *Thanks for the
confirmation... it works! Just a comment, according to the rulebook,
Wizards can learn signs as well (as they are basic magic tricks for them),
wouldn’t it be a bit confusing that the PC Wizard has to add two different
casting professions to be able to drag & drop (one for mage spells and
other for witcher signs). Wouldn’t it be easier to allow mage to add signs
to their list by default? *

Others :

1.     Will surely add an option for this later - *Thanks!*

2.     Lifepath tab will be added, I'm not sure about the level of
automation that will be implemented for now - *Thanks!*

3.     The skills tab is currently under reconstruction, I will keep your
idea in mind. - *:) *

4.     Yes a Gear module is planned later (it's a lot of content to add :)
) - *Will be waiting for it :) *


Thanks a lot and keep up the good work!!


Your overly enthusiat beta-tester,

Mario C.

**Comment by Althea21** [comment]
Hello Mario,

Thank you for your kind words :)
A full ruleset development is indeed time consumming and, as we do it on our free time, real life often come to mess plan but feedback is always welcome to help know how to improve ! 
By the way, you can see the roadmap of planned improvement here : https://github.com/Althea21/witcher_fg_ruleset/projects/1

Your english seems fine to me (but english isn't my mother tongue too ^^). 

Now getting down to business :) :

> 1. The character "main" sheet seems a bit empty... (...)

We don't plan to change the layout yet but when some info will be added in the future (witcher school is a good one ;) ), we'll see how to improve it

> 2. Maybe the Skill tab can also display the BASE + MOD = TOTAL so the it is (...)

This tab is currently under reconstruction, planned improvements so far are :
- list item display as : skill name + base + STAT + bonus(racial, lifepath, ...) = total 
- sortable list (by skill name or by stat)
- make class skill more visible (bold label)
- display something relevant for skill that need double IP to improve.
- class/racial automation may be implemented now or later (depends on free time I get in september ^^)

> 3. Are you planning to add a place where PCs can add and visualize the specific racial PERKS in the main tab or any other tab?

Yes, I'm not sure where and how for now but racial / profession benefit will be displayed somehow

> 4. Shouldn’t VIGOR be displayed only at the SPELLS tab? Instead of both MAIN and SPELLS ?

It was at first but it was confusing during the character creation because not easy to find so I decided to add it in the stat list. It shouldn't be a problem as modifying it in one tab is updating the value in the other

> 5. Will you include an “information button” next to skills/perks and such so that the player can click and read quickly to remember what things do?

Sure why not but as the Gear module it'll come later. 

> 6. Regarding combat. The D&D FG module has it easy, as the attack (...)

Full combat automation is planned but you put your finger on the main difficulty. As it is we cannot reuse the existing mechanics so we have to start from scratch on this. But in the end it should be completly fonctionnal :

- combat tracker / battlemap targeting
- attack/defense resolution 
- damage automation (with resistance and all)
- effects for damage and bonus/malus (on fire, poisonned, staggered, ...)

As you can imagine it's a huge work so be patient :)

> 7. Will you add an “action” button for Actively Dodge or Aim actions, so (...)

This will be possible when effects will be implemented

> 8. Will you add Brawling & Wrestling and Special attack buttons/options/?

I'm not sure what you meant with this one. You normally have all needed combat action (normal/fast/strong attack, parry/block brawling attacks) in the "combat" tab as you can see on this screenshot : https://imgur.com/a/cVEuaIb

> 9. Don’t want to start harassing you with Verbal combat, Wounds, Critical
fumbles, and other stuff yet ☹

Verbal combat is not planned yet (but will be as soon as "normal" combat will be ready :)
Wounds, Critical, will be implemented with the full combat automation.
Fumble are already taken in account (if you fumble on an attack it should mention the according fumble in the chat). 

> [about magical classes] Wouldn’t it be easier to allow mage to add signs to their list by default?

You can add several magical classes on a PC sheet.
Mage can cast spells, signs, and aslo have access to ritual and hexes. 
They're all in their respective "magical classes" because they don't have the same information to display (when you click on the bullet at the end of the line) and they also don't use the same skill. I found it also more clear to have separate list to find what you need when you want to cast something. (you should be able to close/open each magical class by clicking on its title bar)

About casting magic, you can see when you cast a spell that stamina reduction is automatic, and overexertion is taken in account too (for variable stamina like witcher signs, the correct amount must be entered before casting). Recovery action is also available on the magic and combat tabs.


Thanks again for your interest and you feedback :)
Althea

**Comment by MarioCamMen** [comment]
Hey!! Me again :P



Have some spare time and figured I could reply :) All your answers are
super clear and make lots of sense, so I will only reply on those I might
have additional doubts/comments to spare  you from endless mails XD



So... here it goes:

8.     Will you add Brawling & Wrestling and Special attack
buttons/options/?

I'm not sure what you meant with this one. You normally have all needed
combat action (normal/fast/strong attack, parry/block brawling attacks) in
the "combat" tab as you can see on this screenshot :
https://imgur.com/a/cVEuaIb

My bad... I went back again to the "In Depth Combat" seccion in the CORE
rulebook and re-read the whole entry on page 163... just realized that all
those special attacks I was referring to can be covered with no problem
using the mechanics you are planning and just manually setting modifiers in
the field that FG already has for this (left-low corner of the board)

9.     Don’t want to start harassing you with Verbal combat, Wounds,
Critical
fumbles, and other stuff yet ☹


Fumble are already taken in account (if you fumble on an attack it should
mention the according fumble in the chat) – Hell yeah!! I played a bit with
combat and got a fumble… it was calculated perfectly!!

About casting magic, you can see when you cast a spell that stamina
reduction is automatic, and overexertion is taken in account too (for
variable stamina like witcher signs, the correct amount must be entered
before casting). Recovery action is also available on the magic and combat
tabs. – Will play with this one later :)


New comment:

Just one today ;)

I went through some of the monsters and I realized that all the ones I
checked (the first 5) and realized that in the COMBAT tab they have FAST
and STRONG attacks… I remembered that monsters do not those as per the CORE
rule book (page 153) but instead have something called Rate of Fire (ROF)…
Also they have Punck/Kick options and not sure if they should have it if
non-humanoids.


Thanks and take care!! :)

Mario C.

**Comment by Althea21** [comment]
Hi Mario :)

Here some precisions about combat :
- when you add a new weapon, you can custom attack and damage by clicking on the "i" at the end of the line : 
   - you can custom the attack formula (stat, skill and weapon accuracy if needed)
   - you can custom damage by dropping dice on the damage section, eventually a fixed number and melee, punch or kick modifier (or not)
   - enhancement are only informative for now but will be used later with effect and damage resolution
   - on the combat tab, every attack type should already take in account the related modifier of attack type (if not let me know)

- about modifier, you have situationnal modifier implemented : you can see them by clicking on the "+/-" icon in the right toolbar. They all works except the damage ones (will be implemented later)

- about NPC sheet I used the same combat tab than for PC sheet so you have the same options available even if, you are correct, monsters doesn't have access to strong and fast attack. It was made like this to release something fonctionnal faster (who can do more can do less) and will surely be modified later to be more accurate. 

Thank you again for the time spent in testing the ruleset !
Althea

**Comment by MarioCamMen** [comment]
Hi!!



Just playing a bit with the new version :)



Please find some comments below (will try to group them the best I can):



*CHARACTER CREATION:*

   - Man-at-arms "Defining Skill" not showing and pops an error at
   character creation when going to the SKILL tab (see attached)



*SKILLS:*

   - Loved how STA is subtracted after rolling a spell and indicates when
   you are out of STA.
   - REC is also working fine
   - Do you think that some Skills that cost (2) to increment could have
   that "(2)" index next to them? Like Language, Monster Lore, etc.
   - Could you add a "dice roller" for Reputation?
   - What do you think about adding a "Character Lock option" for GM so
   that PCs cannot manipulate their scores (SKILLS/Abilities) when not
   allowed? (During campaign previous to level-up)
   - Skill values can be added now :)



*COMBAT:*

   - Missing Dodge and Reposition defense options (only Parry and Block
   available)
   - Hit location is rolled automatically every time and works perfectly,
   but what about attacks when PC wants to perform a targeted attack?
   - Will Stabilization auto roll when conditions are met?
   - Cannot drag/drop damage to the enemy on Combat Tracker... guess that
   one still WIP due to all the mess of defense and armor calculations, right?
   :)



*CHARACTER SHEET:*

   - How will you approach Crafting/Alchemy? As a separated tab with
   section for recipes and ingredients? or in the Inventory tab add extra
   options (equipped/carried/not carried/diagram/formulae/craft. comp./alch.
   comp.) and auto-sort for easy spotting?
   - Will you add Armor layering option?
   - Will wounds/fumble add the relevant effect upon resolution? (e.g. if
   leg, the movement penalty... if weapon damaged, reduced REL)'
   - Will you add and ADRENALINE option? (pg. 175)
   - Will you add Mutagens as permanent effect?
   - ENC is not auto calculated after adding an item with weight
   - How are you planning to add the Shield? As an option in the Armor
   seccion (combat tab + inventory for ENC calculation)? This one will be
   tricky as it can also be used for attacks and defensive actions :(



*OTHERS:*

   - Will you add a Party Rest feature? How will rest replenish HP/STA?
   - Will Bombs auto-target all body parts? And perform all the damage
   calculation paraphernalia?
   - Will Potions add the effect when drank/used?
   - Will you add a SIZE modifier Bonus/Penalty option somewhere? Or do you
   think the better approach is with the Situational modifier?
   - Same as previous but with ranged attacked :)
   - In weapon creation, where do you declare the type of damage the weapon
   does (P/S/B)?
   - Also, in weapon creation, would you consider adding a "properties"
   option to add Long Reach, Focus (1 or x), Slow reload, etc.?



*PREVIOUS EMAIL:*

   - you can custom the attack formula (stat, skill and weapon accuracy if
   needed) - *It works perfectly!*
   - you can custom damage by dropping dice on the damage section,
   eventually a fixed number and melee, punch or kick modifier (or not) - *It
   works perfectly!*
   - enhancements are only informative for now but will be used later with
   effect and damage resolution - *got it! *
   - on the combat tab, every attack type should already take in account
   the related modifier of attack type (if not let me know) - *It does add
   up every modifier, to the extense of my tests :) *

·  about modifier, you have situational modifier implemented : you can see
them by clicking on the "+/-" icon in the right toolbar. They all works
except the damage ones (will be implemented later) - *got it! *

·  about NPC sheet I used the same combat tab than for PC sheet so you have
the same options available even if, you are correct, monsters doesn't have
access to strong and fast attack. It was made like this to release
something functional faster (who can do more can do less) and will surely
be modified later to be more accurate. - *Awesome!!*



Finally, you are doing an outstanding job! Thanks for your effort!! Promise
I will dig deeper into Magic combat next ;)



Take care!!



Mario C.

**Comment by Althea21** [comment]
Hi Mario, 

Thanks for the new feedback :)

Here's my answers : 

**CHARACTER CREATION :**
> - Man-at-arms "Defining Skill" not showing and pops an error at character creation when going to the SKILL tab (see attached)

Will look at this asap

**SKILLS**
> Do you think that some Skills that cost (2) to increment could have
   that "(2)" index next to them?

Yes it's planned in the skill tab redesign, as putting in bold the class skills and use a visual indicator next to the skill impacted by armor EV malus (like in the DD 3.5 ruleset)

> - Could you add a "dice roller" for Reputation?

Yes, I add this in the todo list 

> - What do you think about adding a "Character Lock option" for GM so that PCs cannot manipulate their scores (SKILLS/Abilities) when not allowed? (During campaign previous to level-up)

Why not, I add this in the list of further evolution, it will be optionnal I think

**COMBAT**
> - Missing Dodge and Reposition defense options (only Parry and Block available)

It's planned, but as it's not weapon dependant I don't know yet if I put these next to parry and block or more global like recovery action. What do you think ?

>  - Hit location is rolled automatically every time and works perfectly, but what about attacks when PC wants to perform a targeted attack?

You can choose to aim using the situationnal modifier (button "+/-" at the top of the right tool bar). If you select a location, the aim modifier is automatically calculated and auto-loc is disabled.

>  - Will Stabilization auto roll when conditions are met?

Yes when effect will be available, death save and all will be automated.

>  - Cannot drag/drop damage to the enemy on Combat Tracker... guess that one still WIP due to all the mess of defense and armor calculations, right? :)

Yes it's not possible while targeting and attack/defense resolution is not done properly

**CHARACTER SHEET** 
> - How will you approach Crafting/Alchemy? As a separated tab with section for recipes and ingredients? or in the Inventory tab add extra options (equipped/carried/not carried/diagram/formulae/craft. comp./alch. comp.) and auto-sort for easy spotting?

I planned to make a specific tab, it will be much more comfortable for classes dedicated to craft. 

> - Will you add Armor layering option ?

Not sure of this, in fact not sure on "how". I think for now you can add all layered armor part and just adjust the SP in consequence. I didn't test it but it should work. But I agre it's not clear to know how much armor cover a certain body part. I have to think on the best way to display this.
 
> - Will wounds/fumble add the relevant effect upon resolution? (e.g. if leg, the movement penalty... if weapon damaged, reduced REL)

It's what I aim for, I hope I will succeed :)

> - Will you add and ADRENALINE option? (pg. 175)

I will certainly add an option for this yes

> - Will you add Mutagens as permanent effect ?

Yes but once again I haven't decided "how" yet. How would you see it displayed on the PC sheet ?

> - ENC is not auto calculated after adding an item with weight

It should be if the item is marked as "carried", if not it's a bug, I'll look into this, thanks for reporting it

> - How are you planning to add the Shield? As an option in the Armor seccion (combat tab + inventory for ENC calculation)? This one will be tricky as it can also be used for attacks and defensive actions :(

This one is tricky indeed and I saw it's often houseruled by GM. I think you can add it in the weapon section to use it for attack/defense AND/OR in the armor section if you want it to provide permanent SP on a specific location. I'm open to any other suggestion :)

**OTHERS:**
> - Will you add a Party Rest feature? How will rest replenish HP/STA ?

I think a full rest should restore REC HP to the players and all their STA. Specific cases (wounds healed by magic or Healing hands) will certainly have to be assessed on a case by case basis by the GM.

> - Will Bombs auto-target all body parts? And perform all the damage calculation paraphernalia ?

Another tricky one. I don't know yet, I think I will consider the how during the damage automation developement.

> - Will Potions add the effect when drank/used?

Yes potion will have an effect(s) section for automation

> - Will you add a SIZE modifier Bonus/Penalty option somewhere? (...)

Do you have a book reference for this ?

> - Same as previous but with ranged attacked :)

Range attack modifiers are already usable with the situationnal modifier  (button "+/-" at the top of the right tool bar). If I missed some please tell me :)

> - In weapon creation, where do you declare the type of damage the weapon does (P/S/B)?

In the damage section of the weapon detail you have a "type" (under the damage dice) to add this

>  - Also, in weapon creation, would you consider adding a "properties" option to add Long Reach, Focus (1 or x), Slow reload, etc.?

In the weapon detail edition, the "effects" under the name is meant to specify these, maybe I should rename it "properties".



Again thank you for your kind words and the effort you put in testing our work :)

~Althea

**Comment by MarioCamMen** [comment]
Hi Althea,

How have you been? Hope you are doing great! I'm attaching my next feedback
since I added some reference pics... take care!!

Cheers,

Mario C.

**Comment by Althea21** [comment]
As we exchange tests result by another way, I'm closing this issue.

**Comment by MarioCamMen** [comment]
Hi!!

I haven't been able to test the last update you shared :( Will Make sure to
schedule it for this weekend!

Sorry about that!

Have a great day!

Mario C.
