### ISSUE TITLE
Lutris/Steam Issues on Linux

### ISSUE THREAD

**Issue by daedmondson** [Althea21/witcher_fg_ruleset#15]
I'm having an issue getting this ruleset to work in fantasygrounds on PopOS! 19.10. Effectively, it's recognized appropriately, but when I go to start up the game, it fails. See below the error message:

USERNAME@pop-os:~/Desktop$ lutris
2020-02-02 14:51:52,198: Running Lutris 0.5.4
2020-02-02 14:51:52,199: Using X.Org
2020-02-02 14:51:52,199: Running Mesa driver 19.2.8 on AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.33.0, 5.3.0-7625-generic, LLVM 9.0.0) (0x67df)
2020-02-02 14:51:52,199: GPU: 1002:67DF 1028:1701 using amdgpu drivers
2020-02-02 14:51:52,214: Vulkan is supported
2020-02-02 14:51:52,215: Updating DXVK versions
2020-02-02 14:51:52,456: Updating D9VK versions
Running /home/USERNAME/.local/share/lutris/runners/wine/lutris-5.0-x86_64/bin/wine /home/USERNAME/Games/fantasy-grounds/drive_c/Program Files (x86)/Fantasy Grounds/FantasyGrounds.exe
esync: up and running.
wine: Unhandled page fault on write access to 06CCB000 at address F7CD4CDA (thread 0009), starting debugger...
Waiting on children
All children gone
Exit with returncode 5
2020-02-02 14:52:11,582: Game still running (state: running)
2020-02-02 14:52:11,582: Stopping Fantasy Grounds (wine)
TypeError: refresh() takes 1 positional argument but 3 were given

**Comment by Althea21** [comment]
Thank you for reporting your issue.

Unfortunately I don't have any Linux setting installed to test it, so it's difficult for me to answer.

I'm going to make some research on my own but did you try posting on the official Fantasy Grounds forum, it seems other people had encounter comparable issues in this thread : https://fantasygrounds.com/forums/showthread.php?22516-Fantasy-Grounds-in-Ubuntu-Linux-WINE

Let me know if you find anything, I will

Regards
~Althea

**Comment by daedmondson** [comment]
Thank you for responding!

Keep in mind - all the other standard rulesets that come with the Fantasy Grounds install (5e, etc.) work perfectly fine on linux using WINE with PlayOnLinux and Lutris. However, it appears I might have isolated the issue to a video card one and this ruleset:
`
002d:fixme:d3d:state_linepattern_w Setting line patterns is not supported in OpenGL core contexts. 
`
I don't know a lot about lua or making rulesets - but I have two questions: 
1) Would it be possible to include an extension with this ruleset? The other rulesets allow us to choose something and this one does not. I haven't seen this in action yet to know how it appears.
2) Might there be something different between this ruleset and the others in regards to communicating with the graphics drivers?

I wish I could assist in anyway - but I don't have any experience with rulesets to begin debugging on my end.

**Comment by Althea21** [comment]
Hello, 

Just a question to make sure : are you running Fantasy Frounds or Fantasy Grounds Unity ?

About your questions : 
1. Extensions are made for specific ruleset. You should be able to use any extension provided specifically for this ruleset (there's none that I know about) or for Core RPG and derived ruleset.
2. This ruleset use the native FG library API and do nothing specific graphic wise, beside adding images and fonts to customize render. 

The only thing I can think about that could cause graphic issues is the specific fonts we use. Every thing else is pretty standard based on the CoreRPG ruleset (xml and lua scripts using CoreRPG library).

It seemed others have encountered problems with font (see Lupine Horror message at the end of this page January 25th, 2018 02:02 : https://www.fantasygrounds.com/forums/showthread.php?22516-Fantasy-Grounds-in-Ubuntu-Linux-WINE/page9). 

Don't know if this could help, but you can download here [the font we use](https://mega.nz/#!i5EkDI5B!Y8JtjrylvVljMtg0Tjgn8KCxWMkQPkVzu85j_cY5RqY)

Regards,
~Althea

**Comment by daedmondson** [comment]
Hi Althea,

I'm running Fantasy Grounds. I gave the fonts a try but nothing seems to be working. I'll close the issue for now. Thank you for trying!
