### ISSUE TITLE
Combat Tracker

### ISSUE THREAD

**Issue by Monesterio** [Althea21/witcher_fg_ruleset#16]
Hi, thanks a lot for your amazing work... and excuse me for my bad English.

The Combat Tracker is not working properly when I target characters and NPCs.
If characters are targeted one each other, all works properly (attack vs defense resolution, damage, etc...) but when a character is in combat with an NPC, combat resolution is not resolved and damage from NPC to Character is not resolved... 

Can you let me know if I am doing something wrong or if there's a bug here?

Thanks in advance for your help.

**Comment by Althea21** [comment]
Hello Monesterio and thank you for downloading and using this ruleset !

No worry, your english is pretty good and I'm not a native english speaker too so... 

I didn't have similar issue. 

In order for me to better understand your problem can you do the following : 
- launch FG and try to reproduce the bug
- when you encounter the problem one or more times, close FG
- then go to the directory "C:\Users\[username]\AppData\Roaming\Fantasy Grounds\" and locate the file console.log and send it to me, I'll examine this ASAP and hopefully had a more precise answer to give you !

Stay safe !
Althea

**Comment by Monesterio** [comment]
Ho Althea;

Thanks a lot for your prompt reply.
Attached you get the console.log you requested.

So, I reproduce the error just as the following:

1. I've open Combat Tracker
2. I add a monster (Arachasae) from NPCs
3. I attack with claws
4. I defend with sword
5. No result for the combat I get.
6. I throw damage dice... and the character has no damage.

Again thank you... and stay safe you too!

Best Regards
JuanMa

**Comment by Althea21** [comment]
I'll try to reproduce with these info, but I didn't get any file attached.
Try to email it to me directly : althea0308@gmail.com

Regards,
Althea

**Comment by Monesterio** [comment]
Hi

Maybe the antivirus locked a .log file, I attach the file again as zipped.

Thank you very much

**Comment by Althea21** [comment]
It's strange I don't see the attack roll in the log... and the defense resolution say "no pending attack"
I cannot try it myself this evening but I'll try tomorrow and send a feedback to you asap.

**Comment by Monesterio** [comment]
Yes, it's so strange...

So, if I attack from a Character to a Character, all works properly but if
I try to resolve a combat with a NPC and a Character... it doesn't work.
I attach the log again with a resolution attack with a Character
agains another one first, and then another with a resolution attack with a
Character and a NPC.

I was thinking about... it's possible that I added the NPCs wrongly to the
Combat Tracker?
I click and drag from PNC library to Combat Tracker...

Thanks a lot for your help and effort

**Comment by Althea21** [comment]
Hello,

I cannot reproduce your problem but I may have an idea of why you encounter this problem : 

When you drag NPC from the main list to the combat tracker it's like you create a copy of the NPC, you may create several in fact and each is a new creature and all are independant.  For exemple if you add 5 bandits, each one will have his own sheet with his own stat that you can adjust (and each one will have his own current HP, bonus/malus and all). If you roll the attack from the original NPC sheet that you opened from the list, you don't use the instance of the NPC in the combat tracker so targeting and all will not work.

When in combat you can open the related NPC (or PC) sheet by clicking at the end of the combat tracker line (see attached image). Then you'll be able to do any action for the character.
![open_sheet_from_ct](https://user-images.githubusercontent.com/1757576/79636532-a7d47a00-8178-11ea-85ae-79795c1173ef.jpg)

Let me know if this resolve your problem or if my explanations wasn't clear !

Thank you and stay safe
Althea

**Comment by Monesterio** [comment]
GREAT!!

It seems that all works properly, thanks a lot for your prompt answer and
your help... and obiously for you great work with this ruleset, it`s
amazing.

Best Regards

**Comment by Althea21** [comment]
I'm glad that it works fine now !

Thank you for all your kind words, it's really heart warming and make all this works worth it :)
Don't hesitate to ask any question, report bugs or give any positive or negative feedback you may have.

I wish you plenty of great games !
Regards,
Althea
