### ISSUE TITLE
ActorManager

### ISSUE THREAD

**Issue by ncasaballe** [Althea21/witcher_fg_ruleset#17]
Greetings, 
I forked this repo to butcher it a bit in an attempt to understand it and eventually develop certain parts to help.

The idea was to start with the workings of Quen using effects...
So i went into the applyDamage function in manager_action_damage.lua but i am unable, for the life of me, to find any documentation regarding both ActorManager and ActionsManager.

So i was wondering if you could point me in the right direction.
I intended to get the target's effects to modify the dmg roll before any other calculation, and then, modify the effect (or remove it) from the target.

**Comment by Althea21** [comment]
Hi ncasaballe,

Thanks for your interest in this ruleset.

ActorManager and ActionsManager are "objects" (unfortunatly, there's nothing close as real object in lua 😢) from the CoreRPG ruleset. Sadly, the developer documentation for Fantasy Grounds is really scarce (You can find some useful reference here : http://www.fantasygrounds.com/refdoc/Comm.xcp, and there : https://www.fantasygrounds.com/wiki/index.php/Developer_Guide_-_Rulesets_-_Interface but nothing CoreRPG related). 

So my method so far is mainly to unzip the coreRPG and 3E rulesets (which is based upon CoreRPG and has similar features I wanted to implement) and dive in their relativeley uncommented code to try to understand how it works... 

You also can ask question on the section of FG forums section dedicated to developpement, some already existing post helped me a lot : https://www.fantasygrounds.com/forums/forumdisplay.php?42-The-Workshop

For the "effects" implementation I plan on having a similar implementation that the 3E/PFRPG ruleset (see their editable spell effects in the "Actions" tab). I didn't really looked into it technically for now as basic combat and damage resolution took me a while to work properly and is not totally complete.
So maybe you should look into the existing 3E ruleset to see how it's done and get an idea of how it works.

Don't hesitate to ask further question if needed.

Stay safe,
Althea
