### ISSUE TITLE
Combat automation critical error

### ISSUE THREAD

**Issue by Hurske** [Althea21/witcher_fg_ruleset#19]
Hello, when using the targeted automation in the combat tracker, whenever I attempt an aimed crit at either the Arm or Leg location, I get this error

Script Error: [string "scripts/manager_action_damage.lua"]:374: attempt to concatenate local 'sFinalDamageMessage' (a nil value)

The head and torso crit damage works correctly

**Comment by Althea21** [comment]
Hi Hurske,
Thank you for reporting this bug.
I'll fix it asap, a new release is coming soon.
Regards,
Althea

**Comment by Althea21** [comment]
I'm closing this one as you confirmed the last release fixed the problem.
