### ISSUE TITLE
Combat automation critical damage modifiers

### ISSUE THREAD

**Issue by Hurske** [Althea21/witcher_fg_ruleset#21]
Hello, I am extremely happy that you fixed the location crit bug. I noticed another when testing out the modifier box. Before the last update, if I had an Aiming location picked, as well as Damage Modifiers picked such as Critical - Simple. It would automatically roll the crit damage on the target in the combat tracker if I skipped the attack and did the damage roll immediately.

As it is now, it does not, and both the highlight selection of aiming modifier and damage modifier stay highlighted and not used in the damage roll, damage is also not applied.

**Comment by Althea21** [comment]
Hi,
Ok I see it's the side effect of another fix. I'll look into this asap.
Thanks for reporting this bug.

**Comment by Althea21** [comment]
Hi Hurske, 

Here's a hot fix for you to test. Unzip it first and then place the .pak file it in your ruleset folder as usual.

[WitcherTRPG.zip](https://github.com/Althea21/witcher_fg_ruleset/files/5040215/WitcherTRPG.zip)

**Comment by Hurske** [comment]
Fantastic work, its looking good. I was doing some testing, and did pull a script error a few times, They damage and everything applies, correctly though. Just not sure what might be causing the error as I am having difficulty duplicating it. 

This is the script I get
Script Error: [string "scripts/manager_combat2.lua"]:178: attempt to index field '?' (a nil value)

I got it from doing a Modifiers damage roll, Aiming at the arm, with a Critical - Difficult. But it does apply the damage correctly.
