### ISSUE TITLE
Error on turn passed

### ISSUE THREAD

**Issue by MMOaddicted** [Althea21/witcher_fg_ruleset#27]
I keep getting an error whenever a turn is passed in the tracker. I am the player here, the GM isn't getting the error. I tried clearing the cache.
Error text below:
Script Error: [string "active"]:1: attempt to call field 'onActiveChanged' (a nil value)
Script Error: [string "active"]:1: attempt to call field 'onActiveChanged' (a nil value)
Runtime Notice: s'Reset all pending attacks.'
Script Error: [string "active"]:1: attempt to call field 'onActiveChanged' (a nil value)
Runtime Notice: s'Reset all pending attacks.'
Runtime Notice: s'Reset all pending attacks.'
Script Error: [string "active"]:1: attempt to call field 'onActiveChanged' (a nil value)
Runtime Notice: s'Reset all pending attacks.'
Runtime Notice: s'Reset all pending attacks.'
Script Error: [string "active"]:1: attempt to call field 'onActiveChanged' (a nil value)
Script Error: [string "active"]:1: attempt to call field 'onActiveChanged' (a nil value)
Runtime Notice: s'Reset all pending attacks.'
Runtime Notice: s'Reset all pending attacks.'
Script Error: [string "active"]:1: attempt to call field 'onActiveChanged' (a nil value)
Script Error: [string "active"]:1: attempt to call field 'onActiveChanged' (a nil value)
Runtime Notice: s'Reset all pending attacks.'
Script Error: [string "active"]:1: attempt to call field 'onActiveChanged' (a nil value)
Runtime Notice: s'Reset all pending attacks.'
Runtime Notice: s'Reset all pending attacks.'
Script Error: [string "active"]:1: attempt to call field 'onActiveChanged' (a nil value)
Runtime Notice: s'Reset all pending attacks.'

**Comment by Althea21** [comment]
Hello,

I've just published a new version (0.6.0) that should fix your problem : https://github.com/Althea21/witcher_fg_ruleset/releases/

Please let me know if this works for you.

Regards,
Althea

**Comment by MMOaddicted** [comment]
Hi there!
The errors are fixed, thank you so much! There is something though that you
may wish to consider changing up in the future, the light creme brown fonts
on the tabs on the right of the character sheet are really hard to read,
perhaps changing the font to black could help? In general, the font colour
is mostly good, the only one that I have some trouble with sometimes is IC
chat but that depends on the monitor and or eyesight of the user.  Thank
you SO MUCH for your hard work on this! I hope R Talsorian games lets you
monetise this ruleset as an official product because you deserve some
renumeration for such good and hard work!

wt., 21 gru 2021 o 11:10 Althea ***@***.***> napisał(a):

**Comment by Althea21** [comment]
Thank you so much for your kind words :)
And thank you for your feedback on the new theme, I've tested it on different monitors and true, sometimes it's not very readable. I'll change that in the next update ^^

I'll close the issue as you problem is fixed.

Have a nice Midinvaerne holidays and stay safe ^^
Althea
